[package]
name = "rae_gfx"
version = "0.1.0"
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"

[features]
default = ["gfx-backend-vulkan", "gfx-backend-metal"]
empty = ["gfx-backend-empty"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
gl = ["gfx-backend-gl"]
metal = ["gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
winit = "0.22.2"
raw-window-handle = "0.3.3"
gfx-hal = "0.5.0"
gfx-backend-empty = { version = "0.5.0", optional = true }
gfx-backend-gl = { version = "0.5.0", optional = true }
gfx-backend-vulkan = { version = "0.5.0", optional = true }

[target.'cfg(windows)'.dependencies]
gfx-backend-dx11 = { version = "0.5.0", optional = true }
gfx-backend-dx12 = { version = "0.5.5", optional = true }

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies]
gfx-backend-metal = { version = "0.5.0", optional = true }

[dev-dependencies]
galvanic-assert = "0.8.7"
