[package]
name = "rae_gfx"
version = "0.1.0"
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"

[features]
default = ["gfx-backend-empty"]
metal = ["gfx-backend-metal"]
gl = ["gfx-backend-gl"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
gfx-hal = "0.5.*"
gfx-backend-empty = { version = "0.5.*", optional = true }
gfx-backend-metal = { version = "0.5.*", optional = true }
gfx-backend-gl = { version = "0.5.*", optional = true }
gfx-backend-dx11 = { version = "0.5.*", optional = true }
gfx-backend-dx12 = { version = "0.5.*", optional = true }
gfx-backend-vulkan = { version = "0.5.*", optional = true }
