[package]
name = "rae_gfx"
version = "0.1.0"
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"

[features]
default = ["gfx-backend-vulkan", "gfx-backend-metal"]
empty = ["gfx-backend-empty"]
dx11 = ["gfx-backend-dx11"]
dx12 = ["gfx-backend-dx12"]
gl = ["gfx-backend-gl"]
metal = ["gfx-backend-metal"]
vulkan = ["gfx-backend-vulkan"]

[dependencies]
rae_app = { git = "https://github.com/DavideCorradiDev/rae_app.git", tag = "v0.1.0" }
raw-window-handle = "0.3.3"
nalgebra = "0.21"
gfx-hal = "0.5"
gfx-backend-empty = { version = "0.5", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
gfx-backend-dx11 = { version = "0.5", optional = true }
gfx-backend-dx12 = { version = "0.5", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
gfx-backend-gl = { version = "0.5", optional = true, features = ["glutin"] }

[target.'cfg(any(target_os = "windows", target_os = "linux"))'.dependencies]
gfx-backend-vulkan = { version = "0.5", optional = true }

[target.'cfg(any(target_os = "macos", all(target_os = "ios", target_arch = "aarch64")))'.dependencies]
gfx-backend-metal = { version = "0.5", optional = true }

[dev-dependencies]
galvanic-assert = "0.8.7"

[build-dependencies]
rae_shader = { git = "https://github.com/DavideCorradiDev/rae_shader.git", tag = "v0.1.2" }

[[example]]
name = "triangle"
path = "examples/triangle.rs"
