name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Check Formatting
      run: cargo +nightly fmt --all -- --check

  build:
    strategy:
      matrix:
        platform:
          - {os: windows-latest, test: true, doc: true}
          - {os: windows-latest, backend: dx11, test: false, doc: false}
          - {os: windows-latest, backend: dx12, test: false, doc: false}
          - {os: ubuntu-latest, backend: opengl, test: false, doc: false}
          - {os: ubuntu-latest, backend: vulkan, test: false, doc: false}
          - {os: macos-latest, backend: metal, test: false, doc: false}

    env:
      RUST_BACKTRACE: 1
      FEATURES: ${{ format(',{0}', matrix.platform.backend ) }}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo features
      run: echo $FEATURES
    - name: Build
      run: cargo build --verbose --features $FEATURES
    - name: Run tests
      if: matrix.platform.test
      run: cargo test --verbose --features $FEATURES
    - name: Generate doc
      if: matrix.platform.doc
      run: cargo doc --no-deps --features $FEATURES
