name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Check Formatting
      run: cargo +nightly fmt --all -- --check

  build:
    strategy:
      matrix:
        platform:
          - {os: windows-latest, test: true, doc: true}
          - {os: windows-latest, options: "--features dx11", test: false, doc: false}
          - {os: windows-latest, options: "--features dx12", test: false, doc: false}
          - {os: ubuntu-latest, options: "--features opengl", test: false, doc: false}
          - {os: ubuntu-latest, options: "--features vulkan", test: false, doc: false}
          - {os: macos-latest, options: "--features metal", test: false, doc: false}

    env:
      RUST_BACKTRACE: 1
      OPTIONS: ${{ matrix.platform.options }}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose $OPTIONS
    - name: Run tests
      if: matrix.platform.test
      run: cargo test --verbose $OPTIONS
    - name: Generate doc
      if: matrix.platform.doc
      run: cargo doc --no-deps $OPTIONS
