name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    env:
      RUST_BACKTRACE: 1
      DISPLAY: ":0"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      run: sudo apt-get update && sudo apt-get install libx11-dev
    - name: Echo DISPLAY 
      run: echo $DISPLAY
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
