name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      sudo apt-get update && sudo apt-get install libxcursor && sudo apt-get install libxi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
